openapi: 3.0.1
info:
  title: "Additional Properties"
  version: "1"
components:
  schemas:
    Popularity:
      type: object
      properties:
        tags:
          type: object
          properties:
            declaredProperty:
              type: string
          required:
            - declaredProperty
          additionalProperties:
            type: object
            properties:
              name:
                type: string
              isPopular:
                type: boolean
            required:
              - name
      required:
        - tags
    StringLists:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    VagueExtras:
      type: object
      properties:
        a:
          type: string
        b:
          type: string
      required:
        - b
      additionalProperties: true
